### ISSUE TITLE
Test commented out

### ISSUE THREAD

**Issue by Stefanie-B** [davidmeijer/python-intermediate-inflammation#5]
https://github.com/davidmeijer/python-intermediate-inflammation/blob/68472f29efb9bb6cc1a5db7e63cd2bba4e1a2e31/tests/test_models.py#L103

This test is currently commented out, consider uncommenting it or removing it.

**Comment by LottePronk** [comment]
Fixed in b34ec2a98af22919492b4dbaddaa6c4388606a58
